### ISSUE TITLE
pip install misses __version__

### ISSUE THREAD

**Issue by mtbannister** [thespacedoctor/rockfinder#2]
Attempting a standard import under python 3.6 produces this error:

    import rockfinder
  File "/Users/bannisterm/miniconda2/envs/panstarrs/lib/python3.6/site-packages/rockfinder/__init__.py", line 1, in <module>
    from __version__ import __version__
ModuleNotFoundError: No module named '__version__'

**Comment by asteroidnerd** [comment]
I used pip install rock finder and it installed ok. I'm running a standard condo installation. But see next issue :-(

**Comment by thespacedoctor** [comment]
Hi guys, needs to be installed under python 2.7 version of anaconda.

Try:

```
conda create -n rockfinder python=2.7 pip
```

Then 

```
source activate rockfinder
pop install rockfinder
```

**Comment by asteroidnerd** [comment]
Guessing that should be
pip install rockfinder?

**Comment by thespacedoctor** [comment]
Ha yes - fat fingers on iPhone!!

**Comment by mtbannister** [comment]
It now goes under python 3.6 :) I'll submit a pull request once I'm sure I got all the details.

**Comment by thespacedoctor** [comment]
Brill! Thanks @mtbannister
